- hosts: kubernetes
  user: root

  tasks:
    - name: deploy regapp on kubernetes
      command: kubectl apply -f regapp-deployment.yml

    - name: create loadbalancer service on kubernetes
      command: kubectl apply -f regapp-service.yml
